classdef Galerkin
    %Galerkin Class for spectral-Galerkin representation of ODE
    %   Contains basic methods for converting between frequency/physical
    %   space, finding eigenfunctions/eigenvalues, plotting the result
    %   assuming axial symmetry, and solving linear systems.
    
    properties
        N
        leg
        neq
        ord
        coeff
        opRhs
        opLhs
        x_fun
    end
    
    methods
        function obj = Galerkin( leg, bc_l, bc_r, rhs, lhs, x_fun )
            obj.neq=numel(bc_l);
            if ~(numel(bc_r)==obj.neq)
                error(['Number of boundary conditions on the left does '...
                    'not match number of boundary conditions on the right']);
            end
            obj.coeff=cell(obj.neq,1);
            obj.N=leg.N;
            obj.leg=leg;
            obj.x_fun=x_fun;
            for i=1:obj.neq
                obj.ord(i)=2*numel(bc_l{i});
                if ~(2*numel(bc_r{i})==obj.ord(i))
                    error(['%d variable has different number of boundary'...
                        ' conditions one the left and on the right'],i);
                end
                switch obj.ord(i)
                    case 4
                        A=zeros(4); 
                        A0=zeros(4,1);
                        c_=zeros(obj.N-3,4);
                        for p=0:obj.N-4
                            for j=1:4
                                A(1,j)=bc_l{i}{1}(...
                                    leg.L(p+1+j,1),leg.dL(p+1+j,1),...
                                    leg.d2L(p+1+j,1),leg.d3L(p+1+j,1) );
                                A(2,j)=bc_l{i}{2}(...
                                    leg.L(p+1+j,1),leg.dL(p+1+j,1),...
                                    leg.d2L(p+1+j,1),leg.d3L(p+1+j,1) );
                                A(3,j)=bc_r{i}{1}(...
                                    leg.L(p+1+j,end),leg.dL(p+1+j,end),...
                                    leg.d2L(p+1+j,end),leg.d3L(p+1+j,end) );
                                A(4,j)=bc_r{i}{2}(...
                                    leg.L(p+1+j,end),leg.dL(p+1+j,end),...
                                    leg.d2L(p+1+j,end),leg.d3L(p+1+j,end) );
                            end
                            A0(1)=bc_l{i}{1}(...
                                leg.L(p+1,1),leg.dL(p+1,1),...
                                leg.d2L(p+1,1),leg.d3L(p+1,1) );
                            A0(2)=bc_l{i}{2}(...
                                leg.L(p+1,1),leg.dL(p+1,1),...
                                leg.d2L(p+1,1),leg.d3L(p+1,1) );
                            A0(3)=bc_r{i}{1}(...
                                leg.L(p+1,end),leg.dL(p+1,end),...
                                leg.d2L(p+1,end),leg.d3L(p+1,end) );
                            A0(4)=bc_r{i}{2}(...
                                leg.L(p+1,end),leg.dL(p+1,end),...
                                leg.d2L(p+1,end),leg.d3L(p+1,end) );
                            c_(p+1,:)=-(A\A0)';
                        end
                    case 2
                        A=zeros(2); 
                        A0=zeros(2,1);
                        c_=zeros(obj.N-1,2);
                        for p=0:obj.N-2
                            for j=1:2
                                A(1,j)=bc_l{i}{1}(...
                                    leg.L(p+1+j,1),leg.dL(p+1+j,1));
                                A(2,j)=bc_r{i}{1}(...
                                    leg.L(p+1+j,end),leg.dL(p+1+j,end));
                            end
                            A0(1)=bc_l{i}{1}(...
                                leg.L(p+1,1),leg.dL(p+1,1));
                            A0(2)=bc_r{i}{1}(...
                                leg.L(p+1,end),leg.dL(p+1,end));
                            c_(p+1,:)=-(A\A0)';
                        end
                    otherwise
                        error('%d equation must be order 2 or 4',i);
                end
                obj.coeff{i}=c_;
            end
            obj.opRhs=cell(obj.neq,obj.neq);
            obj.opLhs=cell(obj.neq,obj.neq);
            for i=1:obj.neq
                for j=1:obj.neq
                    L_=zeros(obj.N-obj.ord(i)+1,obj.N-obj.ord(j)+1);
                    A_=zeros(obj.N-obj.ord(i)+1,obj.N-obj.ord(j)+1);
                    for q=0:obj.N-obj.ord(j)
                        if obj.ord(i)==4 && obj.ord(j)==4
                            phi_qj=( leg.L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.L(q+5,:) )';
                            dphi_qj=( leg.dL(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.dL(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.dL(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.dL(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.dL(q+5,:) )';
                            d2phi_qj=( leg.d2L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d2L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d2L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.d2L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.d2L(q+5,:) )';
                            d3phi_qj=( leg.d3L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d3L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d3L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.d3L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.d3L(q+5,:) )';
                            d4phi_qj=( leg.d4L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d4L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d4L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.d4L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.d4L(q+5,:) )';
                            rhs_ij_phi_qj=rhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj,...
                                dphi_qj,...
                                d2phi_qj,...
                                d3phi_qj,...
                                d4phi_qj);
                            lhs_ij_phi_qj=lhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj,...
                                dphi_qj,...
                                d2phi_qj);
                            rr=leg.FLegT(rhs_ij_phi_qj);
                            ll=leg.FLegT(lhs_ij_phi_qj);
                            for p=0:obj.N-obj.ord(i)
                                L_(p+1,q+1)=leg.norm2(p+1)*rr(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*rr(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*rr(p+3)...
                                    +obj.coeff{i}(p+1,3)*leg.norm2(p+4)*rr(p+4)...
                                    +obj.coeff{i}(p+1,4)*leg.norm2(p+5)*rr(p+5);
                                A_(p+1,q+1)=leg.norm2(p+1)*ll(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*ll(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*ll(p+3)...
                                    +obj.coeff{i}(p+1,3)*leg.norm2(p+4)*ll(p+4)...
                                    +obj.coeff{i}(p+1,4)*leg.norm2(p+5)*ll(p+5);
                            end
                        elseif obj.ord(i)==4 && obj.ord(j)==2
                            phi_qj=( leg.L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.L(q+3,:) )';
                            dphi_qj=( leg.dL(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.dL(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.dL(q+3,:) )';
                            d2phi_qj=( leg.d2L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d2L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d2L(q+3,:) )';
                            rhs_ij_phi_qj=rhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj,...
                                dphi_qj,...
                                d2phi_qj);
                            lhs_ij_phi_qj=lhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj);
                            rr=leg.FLegT(rhs_ij_phi_qj);
                            ll=leg.FLegT(lhs_ij_phi_qj);
                            for p=0:obj.N-obj.ord(i)
                                L_(p+1,q+1)=leg.norm2(p+1)*rr(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*rr(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*rr(p+3)...
                                    +obj.coeff{i}(p+1,3)*leg.norm2(p+4)*rr(p+4)...
                                    +obj.coeff{i}(p+1,4)*leg.norm2(p+5)*rr(p+5);
                                A_(p+1,q+1)=leg.norm2(p+1)*ll(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*ll(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*ll(p+3)...
                                    +obj.coeff{i}(p+1,3)*leg.norm2(p+4)*ll(p+4)...
                                    +obj.coeff{i}(p+1,4)*leg.norm2(p+5)*ll(p+5);
                            end
                        elseif obj.ord(i)==2 && obj.ord(j)==4
                            phi_qj=( leg.L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.L(q+5,:) )';
                            dphi_qj=( leg.dL(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.dL(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.dL(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.dL(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.dL(q+5,:) )';
                            d2phi_qj=( leg.d2L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d2L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d2L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.d2L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.d2L(q+5,:) )';
                            d3phi_qj=( leg.d3L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d3L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d3L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.d3L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.d3L(q+5,:) )';
                            d4phi_qj=( leg.d4L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d4L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d4L(q+3,:)...
                                +obj.coeff{j}(q+1,3)*leg.d4L(q+4,:)...
                                +obj.coeff{j}(q+1,4)*leg.d4L(q+5,:) )';
                            rhs_ij_phi_qj=rhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj,...
                                dphi_qj,...
                                d2phi_qj,...
                                d3phi_qj,...
                                d4phi_qj);
                            lhs_ij_phi_qj=lhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj,...
                                dphi_qj,...
                                d2phi_qj);
                            rr=leg.FLegT(rhs_ij_phi_qj);
                            ll=leg.FLegT(lhs_ij_phi_qj);
                            for p=0:obj.N-obj.ord(i)
                                L_(p+1,q+1)=leg.norm2(p+1)*rr(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*rr(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*rr(p+3);
                                A_(p+1,q+1)=leg.norm2(p+1)*ll(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*ll(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*ll(p+3);
                            end
                        elseif obj.ord(i)==2 && obj.ord(j)==2
                            phi_qj=( leg.L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.L(q+3,:) )';
                            dphi_qj=( leg.dL(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.dL(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.dL(q+3,:) )';
                            d2phi_qj=( leg.d2L(q+1,:)...
                                +obj.coeff{j}(q+1,1)*leg.d2L(q+2,:)...
                                +obj.coeff{j}(q+1,2)*leg.d2L(q+3,:) )';
                            rhs_ij_phi_qj=rhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj,...
                                dphi_qj,...
                                d2phi_qj);
                            lhs_ij_phi_qj=lhs{i}{j}(...
                                x_fun(leg.x),...
                                phi_qj);
                            rr=leg.FLegT(rhs_ij_phi_qj);
                            ll=leg.FLegT(lhs_ij_phi_qj);
                            for p=0:obj.N-obj.ord(i)
                                L_(p+1,q+1)=leg.norm2(p+1)*rr(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*rr(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*rr(p+3);
                                A_(p+1,q+1)=leg.norm2(p+1)*ll(p+1)...
                                    +obj.coeff{i}(p+1,1)*leg.norm2(p+2)*ll(p+2)...
                                    +obj.coeff{i}(p+1,2)*leg.norm2(p+3)*ll(p+3);
                            end

                        else
                            error('Orders are not 4/2');
                        end
                    end
                    obj.opLhs{i,j}=A_;
                    obj.opRhs{i,j}=L_;
                end
            end
            obj.opRhs=cell2mat(obj.opRhs);
            obj.opLhs=cell2mat(obj.opLhs);
        end
        
        function v = FPhiLegT( obj, u )
        %FPhiLegT Foward phi-Legendre transform    
            if ~(numel(u)==obj.neq)
                error(['Number of components does not match '...
                    'Galerkin decomposition']);
            end
            v=cell(obj.neq,1);
            for i=1:obj.neq
               vv=((0:obj.N)'+0.5).*(obj.leg.L*(obj.leg.w.*u{i}));
               vv(obj.N+1)=obj.N/(2*obj.N+1)*vv(obj.N+1);
               switch size(obj.coeff{i},2)
                   case 4
                       v{i}=zeros(obj.N-3,1);
                       for k=0:obj.N-4
                            v{i}(k+1)=obj.leg.norm2(k+1)*vv(k+1)...
                             +obj.leg.norm2(k+2)*obj.coeff{i}(k+1,1)*vv(k+2)...
                             +obj.leg.norm2(k+3)*obj.coeff{i}(k+1,2)*vv(k+3)...
                             +obj.leg.norm2(k+4)*obj.coeff{i}(k+1,3)*vv(k+4)...
                             +obj.leg.norm2(k+5)*obj.coeff{i}(k+1,4)*vv(k+5);
                       end 
                   case 2
                       v{i}=zeros(obj.N-1,2);
                       for k=0:obj.N-2
                            v{i}(k+1)=obj.leg.norm2(k+1)*vv(k+1)...
                             +obj.leg.norm2(k+2)*obj.coeff{i}(k+1,1)*vv(k+2)...
                             +obj.leg.norm2(k+3)*obj.coeff{i}(k+1,2)*vv(k+3);
                       end
                   otherwise
                       error('Unexpected size of c(%d,:)',i);
               end
            end
            v=cell2mat(v);
        end
        
        function [u,du,d2u,d3u] = BPhiLegT( obj, v )
        %BPhiLegT Backward phi-Legendre transform    
            switch nargout
                case 1
                    u=cell(obj.neq,1);
                    Ni=@(i) (obj.N-1)*(size(obj.coeff{i},2)==2)...
                        +(obj.N-3)*(size(obj.coeff{i},2)==4);
                    n=0;
                    for i=1:obj.neq
                        if size(obj.coeff{i},2)==4
                            phi=obj.leg.L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.L(5:obj.N+1,:);
                        elseif size(obj.coeff{i},2)==2
                            phi=obj.leg.L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N+1,:);
                        end
                        u{i}=( v(n+1:n+Ni(i))'*phi )';
                        n=n+Ni(i);
                    end
                case 2
                    u=cell(obj.neq,1);
                    du=cell(obj.neq,1);
                    Ni=@(i) (obj.N-1)*(size(obj.coeff{i},2)==2)...
                        +(obj.N-3)*(size(obj.coeff{i},2)==4);
                    n=0;
                    for i=1:obj.neq
                        if size(obj.coeff{i},2)==4
                            phi=obj.leg.L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.L(5:obj.N+1,:);
                            dphi=obj.leg.dL(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.dL(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.dL(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.dL(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.dL(5:obj.N+1,:);
                        elseif size(obj.coeff{i},2)==2
                            phi=obj.leg.L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N+1,:);
                            dphi=obj.leg.dL(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.dL(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.dL(3:obj.N+1,:);
                        end
                        u{i}=( v(n+1:n+Ni(i))'*phi )';
                        du{i}=( v(n+1:n+Ni(i))'*dphi )';
                        n=n+Ni(i);
                    end
                case 3
                    u=cell(obj.neq,1);
                    du=cell(obj.neq,1);
                    d2u=cell(obj.neq,1);
                    Ni=@(i) (obj.N-1)*(size(obj.coeff{i},2)==2)...
                        +(obj.N-3)*(size(obj.coeff{i},2)==4);
                    n=0;
                    for i=1:obj.neq
                        if size(obj.coeff{i},2)==4
                            phi=obj.leg.L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.L(5:obj.N+1,:);
                            dphi=obj.leg.dL(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.dL(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.dL(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.dL(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.dL(5:obj.N+1,:);
                            d2phi=obj.leg.d2L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.d2L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.d2L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.d2L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.d2L(5:obj.N+1,:);
                        elseif size(obj.coeff{i},2)==2
                            phi=obj.leg.L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N+1,:);
                            dphi=obj.leg.dL(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.dL(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.dL(3:obj.N+1,:);
                            d2phi=obj.leg.d2L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.d2L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.d2L(3:obj.N+1,:);
                        end
                        u{i}=( v(n+1:n+Ni(i))'*phi )';
                        du{i}=( v(n+1:n+Ni(i))'*dphi )';
                        d2u{i}=( v(n+1:n+Ni(i))'*d2phi )';
                        n=n+Ni(i);
                    end
                case 4
                    u=cell(obj.neq,1);
                    du=cell(obj.neq,1);
                    d2u=cell(obj.neq,1);
                    d3u=cell(obj.neq,1);
                    Ni=@(i) (obj.N-1)*(size(obj.coeff{i},2)==2)...
                        +(obj.N-3)*(size(obj.coeff{i},2)==4);
                    n=0;
                    for i=1:obj.neq
                        if size(obj.coeff{i},2)==4
                            phi=obj.leg.L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.L(5:obj.N+1,:);
                            dphi=obj.leg.dL(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.dL(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.dL(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.dL(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.dL(5:obj.N+1,:);
                            d2phi=obj.leg.d2L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.d2L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.d2L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.d2L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.d2L(5:obj.N+1,:);
                            d3phi=obj.leg.d3L(1:obj.N-3,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.d3L(2:obj.N-2,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.d3L(3:obj.N-1,:)...
                                +diag(obj.coeff{i}(:,3))*obj.leg.d3L(4:obj.N,:)...
                                +diag(obj.coeff{i}(:,4))*obj.leg.d3L(5:obj.N+1,:);
                        elseif size(obj.coeff{i},2)==2
                            phi=obj.leg.L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.L(3:obj.N+1,:);
                            dphi=obj.leg.dL(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.dL(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.dL(3:obj.N+1,:);
                            d2phi=obj.leg.d2L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.d2L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.d2L(3:obj.N+1,:);
                            d3phi=obj.leg.d3L(1:obj.N-1,:)+...
                                diag(obj.coeff{i}(:,1))*obj.leg.d3L(2:obj.N,:)...
                                +diag(obj.coeff{i}(:,2))*obj.leg.d3L(3:obj.N+1,:);
                        end
                        u{i}=( v(n+1:n+Ni(i))'*phi )';
                        du{i}=( v(n+1:n+Ni(i))'*dphi )';
                        d2u{i}=( v(n+1:n+Ni(i))'*d2phi )';
                        d3u{i}=( v(n+1:n+Ni(i))'*d3phi )';
                        n=n+Ni(i);
                    end
            end
            
        end
        
        function beta = eigenvalues( obj, nev )
        %eigenvalues finds first nev eigenvalues    
           beta_=eig(obj.opRhs,obj.opLhs);
           [~,ind]=sort(real(beta_),'descend'); 
           beta=beta_(ind(1:nev));
        end
        
        function [beta,u,du,d2u,d3u] = eigenfunctions( obj, nev, flag )
        %eigenfunctions finds first nev eigenfunctions and derivatives
            if strcmp(flag,'normal') || strcmp(flag,'raw')
                [v,beta]=eig(obj.opRhs,obj.opLhs);
            elseif strcmp(flag,'dual')
                [v,beta]=eig(obj.opRhs',obj.opLhs');
            else
                error('Last argument must be normal, dual or raw.');
            end
           [re_beta,ind]=sort(real(diag(beta)),'descend'); 
            sorted_v=zeros(size(v)); 
            sorted_beta=zeros(size(beta));
            for j=1:length(re_beta)
                sorted_v(:,j)=v(:,ind(j));  
                sorted_beta(j,j)=beta(ind(j),ind(j));
            end
            v=sorted_v(:,1:nev); 
            beta=diag(sorted_beta(1:nev,1:nev));
            if strcmp(flag,'dual') || strcmp(flag,'raw')
                u=v;
                if nargout>2
                    error('Invalid number of requested ouput.');
                end
                return;
            end
            u=cell(nev,1);
            switch nargout
                case 2
                    for i=1:nev
                        u{i}=obj.BPhiLegT(v(:,i));
                    end
                case 3
                    du=cell(nev,1);
                    for i=1:nev
                        [u{i},du{i}]=obj.BPhiLegT(v(:,i));
                    end
                case 4
                    du=cell(nev,1);
                    d2u=cell(nev,1);
                    for i=1:nev
                        [u{i},du{i},d2u{i}]=obj.BPhiLegT(v(:,i));
                    end
                case 5
                    du=cell(nev,1);
                    d2u=cell(nev,1);
                    d3u=cell(nev,1);
                    for i=1:nev
                        [u{i},du{i},d2u{i},d3u{i}]=obj.BPhiLegT(v(:,i));
                    end
            end
        end
        
        function h = plot_as_flat( obj, u, p_vals, m, flag )
        %plot_as_flat plots Re ( u(x) e^{i m t} )
        % assumes x is vertical, t is horizontal, t in p_vals interval
           [pp,zz]=meshgrid(p_vals,obj.x_fun(obj.leg.x));
           uu=zeros(size(pp));
           if strcmp(flag,'real')
               for j=1:length(p_vals)
                   uu(:,j)=real(u)*cos(m*p_vals(j))-imag(u)*sin(m*p_vals(j));
               end
           elseif strcmp(flag,'imag')
               for j=1:length(p_vals)
                   uu(:,j)=real(u)*sin(m*p_vals(j))+imag(u)*cos(m*p_vals(j));
               end
           else
               error('Last argument must be real or imag.');
           end
           h=contourf(pp,zz,uu);
        end
        
        function h = plot_as_polar( obj, u, p_vals, m, flag )
        %plot_as_polar plots Re ( u(x) e^{i m t} )
        % assumes x is radial, t is circular (so pvals is 0:dt:2*pi)
           [pp,zz]=meshgrid(p_vals,obj.x_fun(obj.leg.x));
           uu=zeros(size(pp));
           if strcmp(flag,'real')
               for j=1:length(p_vals)
                   uu(:,j)=real(u)*cos(m*p_vals(j))-imag(u)*sin(m*p_vals(j));
               end
           elseif strcmp(flag,'imag')
               for j=1:length(p_vals)
                   uu(:,j)=real(u)*sin(m*p_vals(j))+imag(u)*cos(m*p_vals(j));
               end
           else
               error('Last argument must be real or imag.');
           end
           [xx,yy,uu]=pol2cart(pp,zz,uu);
           h=contourf(xx,yy,uu);
        end
        
        function [u,du,d3u] = solve_linear(obj, k, f)
        %solve_linear solves the system (kA-L)u=f
            f_=obj.FPhiLegT(f);
            u_=(k*obj.opLhs-obj.opRhs)\f_;
            [u,du,d3u]=obj.BPhiLegT(u_);
        end
        
    end
    
end

